- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/configs.yml
    - include: tasks/vscode.yml
    - include: tasks/docker.yml
