- name: Install docker dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Get gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
 
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Get Ubuntu version
  shell: lsb_release -cs
  register: ubuntu_name

- name: Add docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_name.stdout }} stable"
        state: present

- name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io


- name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

